{% set name = "pyobjc-core" %}
{% set version = "8.5" %}
{% set sha256 = "704c275439856c0d1287469f0d589a7d808d48b754a93d9ce5415d4eaf06d576" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fix_for_conda_build.diff

build:
  number: 0
  skip: true  # [not osx or py<36 or (arm64 and py < 38)]
  script: 
    # force pyobjc to use conda-forge's chosen SDK
    - export CFLAGS="${CFLAGS} -isysroot ${SDKROOT:-$CONDA_BUILD_SYSROOT}"
    # force ignoring invalid compiler flag (-Wl,-export-dynamic)
    - export CFLAGS="${CFLAGS} -Wno-unused-command-line-argument"  # [py == 37 or py == 38]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - libffi
    - patch
  host:
    - python
    - pip
    - wheel
    - setuptools
    - libffi
  run:
    - python
    - libffi

test:
  imports:
    - PyObjCTools
    - objc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ronaldoussoren/pyobjc
  license: MIT
  summary: 'Python<->ObjC Interoperability Module'
  license_family: MIT
  license_file: License.txt
  dev_url: https://github.com/ronaldoussoren/pyobjc/tree/master/pyobjc-core
  doc_url: https://github.com/ronaldoussoren/pyobjc/blob/master/pyobjc-core/README.txt

extra:
  recipe-maintainers:
    - kastman
