{% set name = "pyobjc-core" %}
{% set version = "8.1" %}
{% set sha256 = "920914a1a4cd4f8a54babe93f0b4e4cd93b51d11ae38d8ef17f5edb603b7a949" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:                # [osx and arm64]
    - fix_ffi_fcfc.patch  # [osx and arm64]

build:
  number: 0
  skip: true  # # [not osx or py2k or (arm64 and py < 38)]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - libffi
  host:
    - python
    - pip
    - wheel
    - setuptools
    - libffi
  run:
    - python
    - libffi
    - setuptools

test:
  imports:
    - PyObjCTools
    - objc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ronaldoussoren/pyobjc
  license: MIT
  summary: 'Python<->ObjC Interoperability Module'
  license_family: MIT
  license_file: License.txt
  dev_url: https://github.com/ronaldoussoren/pyobjc/tree/master/pyobjc-core
  doc_url: https://github.com/ronaldoussoren/pyobjc/blob/master/pyobjc-core/README.txt

extra:
  recipe-maintainers:
    - kastman
