{% set name = "pyobjc-core" %}
{% set version = "4.2" %}
{% set sha256 = "3852f66ea2c79e0575c03f068b19d2a1a6e06c24807fbb156a5b7ce4242a6cf0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not osx]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - PyObjCTools
    - objc

about:
  home: http://pyobjc.sourceforge.net/
  license: MIT
  summary: 'Python<->ObjC Interoperability Module'
  license_family: MIT
  license_file: License.txt

extra:
  recipe-maintainers:
    - kastman
