{% set name = "pyobjc-core" %}
{% set version = "4.1" %}
{% set sha256 = "e42d3558b65485f896e272e48e108d4df8ccd7f130f552dddb4a47732dd0ee65" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not osx]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - PyObjCTools
    - objc

about:
  home: http://pyobjc.sourceforge.net/
  license: MIT
  summary: 'Python<->ObjC Interoperability Module'
  license_family: MIT
  license_file: License.txt

extra:
  recipe-maintainers:
    - kastman
