travis:
  secure:
    BINSTAR_TOKEN: d8PJPKOumgOkNG152WT1lj1bIC2Y/zCFnoziYhIfqly8g/ByagoUGBn+6bblBCdpdGzrUznlytWD1vcOoWafLGEmNBNF697LEfAerDZoikMLDFYuRpCtRDoaZF0RMQ9KNs26q9UVlryEfHRLg2cZ/0v1FMQmqL3fdTuIiCfV3RmCraXoiepacp07u3+BIDCpEctBJEsPMpQdPNHxddx4WOqquvv/SqdUUSl2gl9iJ/frpR9cad4ARWnRkQ+Kbi1ISEzv/+dRaUYpTynm2k0kqjkvuYOKKFRmtgEPWpqB1Ea3MfS3eBuR2qr0SImYYytvbJACnbhQofTW16EmZvKKTme3oPWZc0nIL4Z8ZEVFG8w/nbdYllnwsrhmFenXrmvMUkRij0mw07kQUrqNTB0FTKjS0jiUtGHFrQw/H0dI6buC100fgaS4F0iv+5nDdIcfv6giZwMTE3ryxtZkXy7nXalMMiqutDx0HyG8MxmdJNqnEq0m+ZqiYuz32L3Q5uHsEg2+OO1JeNwACno5z3XJyxmHWiV5aKo67YQ43tuRzebMHzVkgE/N8Bm9Uc3kCCzkY4tiEEyKZJCjG64cxLhCPqxXM+HpQtX9tNfEVpWu+XosktpnazLwkzKvGRwmVVuR/WPM2HrK5eCMC4rwiOtnVB0c1vuiUP5eiy44wTklEjQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
